export const COOKIE_NOTICE_ACCEPTED = 'cookie-notice-accepted';
export const DEFAULT_DOMAIN_TLD = 'com';
export const DEFAULT_DOMAIN_PRICE = '12.99';
export const DEFAULT_DOMAIN_TERM = 12;
export const DEFAULT_PRIVACY_PRODUCT = {
	type: '2092',
	category: 'domains',
	currency: 'USD',
	privacyAvailable: false,
	terms: [
		{
			price: '8.99',
			basePrice: '8.99',
			promos: 'dir_base01_a',
			offerId: 404645,
			regularRate: 0.75,
			monthlyPrice: 0.75,
			discount: '0%',
			term: 12,
			masters: '2092',
		},
		{
			price: '17.98',
			basePrice: '17.98',
			promos: 'dir_base01_24',
			offerId: 443933,
			regularRate: 0.75,
			monthlyPrice: 0.75,
			discount: '0%',
			term: 24,
			masters: '2092',
		},
		{
			price: '26.97',
			basePrice: '26.97',
			promos: 'dir_base01_36',
			offerId: 443936,
			regularRate: 0.75,
			monthlyPrice: 0.75,
			discount: '0%',
			term: 36,
			masters: '2092',
		},
		{
			price: '35.96',
			basePrice: '35.96',
			promos: 'dir_base01_48',
			offerId: 449651,
			regularRate: 0.75,
			monthlyPrice: 0.75,
			discount: '0%',
			term: 48,
			masters: '2092',
		},
		{
			price: '44.95',
			basePrice: '44.95',
			promos: 'dir_base01_60',
			offerId: 443939,
			regularRate: 0.75,
			monthlyPrice: 0.75,
			discount: '0%',
			term: 60,
			masters: '2092',
		},
	],
	level: 'dir_base01_',
	action: 'add',
	propertyID: '47',
	isInternalUser: false,
	name: 'Domain Privacy + Protection',
};
export const VALID_DOMAIN_TLDS = [
	'com',
	'net',
	'org',
	'tech',
	'space',
	'online',
	'store',
	'site',
	'website',
	'blog',
	'co',
	'me',
	'live',
	'us',
	'design',
	'ca',
	'biz',
	'host',
	'press',
	'io',
	'club',
	'info',
];
