import extractDomain from './extractDomain';

const FAKE = {
	fakeDomains: [
		{
			domainInfo: {
				phase: 'general',
				suggestion: false,
				sld: 'shakibisawesome',
				tld: 'tech',
				availability: true,
				premium: false,
				registry_premium: false,
				aftermarket: false,
				tmch: false,
				domain: 'shakibisawesome.tech',
				domain_partner: 'rodas',
			},
			propertyID: '47',
			name: '.tech',
			action: 'add',
			currency: 'USD',
			type: 'domains',
			level: 'tech',
			category: 'domains',
			privacyAvailable: true,
			terms: [
				{
					price: '4.99',
					basePrice: '4.99',
					promos: 'tech_register_499_1o',
					offerId: 163013,
					term: 12,
					masters: '1853',
				},
				{
					price: '31.98',
					basePrice: '31.98',
					promos: 'tech_register_3198_2o',
					offerId: 495256,
					term: 24,
					masters: '1853',
				},
				{
					price: '58.97',
					basePrice: '58.97',
					promos: 'tech_register_5897_3o',
					offerId: 506001,
					term: 36,
					masters: '1853',
				},
				{
					price: '85.96',
					basePrice: '85.96',
					promos: 'tech_register_8596_4o',
					offerId: 506006,
					term: 48,
					masters: '1853',
				},
				{
					price: '112.95',
					basePrice: '112.95',
					promos: 'tech_register_11295_5o',
					offerId: 506011,
					term: 60,
					masters: '1853',
				},
			],
		},
		{
			domainInfo: {
				phase: 'general',
				suggestion: false,
				sld: 'shakibisawesome',
				tld: 'space',
				availability: true,
				premium: false,
				registry_premium: false,
				aftermarket: false,
				tmch: false,
				domain: 'shakibisawesome.space',
				domain_partner: 'rodas',
			},
			propertyID: '47',
			name: '.space',
			action: 'add',
			currency: 'USD',
			type: 'domains',
			level: 'space',
			category: 'domains',
			privacyAvailable: true,
			terms: [
				{
					price: '2.99',
					basePrice: '2.99',
					promos: 'space_register_299_1o',
					offerId: 164088,
					term: 12,
					masters: '1812',
				},
				{
					price: '14.98',
					basePrice: '14.98',
					promos: 'space_register_1498_2o',
					offerId: 174994,
					term: 24,
					masters: '1812',
				},
				{
					price: '26.97',
					basePrice: '26.97',
					promos: 'space_register_2697_3o',
					offerId: 356231,
					term: 36,
					masters: '1812',
				},
				{
					price: '38.96',
					basePrice: '38.96',
					promos: 'space_register_3896_4o',
					offerId: 356234,
					term: 48,
					masters: '1812',
				},
				{
					price: '50.95',
					basePrice: '50.95',
					promos: 'space_register_5095_5o',
					offerId: 477282,
					term: 60,
					masters: '1812',
				},
			],
		},
		{
			domainInfo: {
				phase: 'general',
				suggestion: false,
				sld: 'shakibisawesome',
				tld: 'online',
				availability: true,
				premium: false,
				registry_premium: false,
				aftermarket: false,
				tmch: false,
				domain: 'shakibisawesome.online',
				domain_partner: 'rodas',
			},
			propertyID: '47',
			name: '.online',
			action: 'add',
			currency: 'USD',
			type: 'domains',
			level: 'online',
			category: 'domains',
			privacyAvailable: true,
			terms: [
				{
					price: '5.99',
					basePrice: '5.99',
					promos: 'online_register_599_1o',
					offerId: 164073,
					term: 12,
					masters: '1868',
				},
				{
					price: '19.98',
					basePrice: '19.98',
					promos: 'online_register_1998_2o',
					offerId: 166739,
					term: 24,
					masters: '1868',
				},
				{
					price: '33.97',
					basePrice: '33.97',
					promos: 'online_register_3397_3o',
					offerId: 174715,
					term: 36,
					masters: '1868',
				},
				{
					price: '47.96',
					basePrice: '47.96',
					promos: 'online_register_4796_4o',
					offerId: 174718,
					term: 48,
					masters: '1868',
				},
				{
					price: '61.95',
					basePrice: '61.95',
					promos: 'online_register_6195_5o',
					offerId: 174721,
					term: 60,
					masters: '1868',
				},
			],
		},
		{
			domainInfo: {
				phase: 'general',
				suggestion: false,
				sld: 'shakibisawesome',
				tld: 'store',
				availability: true,
				premium: false,
				registry_premium: false,
				aftermarket: false,
				tmch: false,
				domain: 'shakibisawesome.store',
				domain_partner: 'rodas',
			},
			propertyID: '47',
			name: '.store',
			action: 'add',
			currency: 'USD',
			type: 'domains',
			level: 'store',
			category: 'domains',
			privacyAvailable: true,
			terms: [
				{
					price: '9.99',
					basePrice: '9.99',
					promos: 'store_register_999_1o',
					offerId: 166782,
					term: 12,
					masters: '1992',
				},
				{
					price: '29.98',
					basePrice: '29.98',
					promos: 'store_register_2998_2o',
					offerId: 165281,
					term: 24,
					masters: '1992',
				},
				{
					price: '49.97',
					basePrice: '49.97',
					promos: 'store_register_4997_3o',
					offerId: 174925,
					term: 36,
					masters: '1992',
				},
				{
					price: '69.96',
					basePrice: '69.96',
					promos: 'store_register_6996_4o',
					offerId: 174928,
					term: 48,
					masters: '1992',
				},
				{
					price: '89.95',
					basePrice: '89.95',
					promos: 'store_register_8995_5o',
					offerId: 174931,
					term: 60,
					masters: '1992',
				},
			],
		},
		{
			domainInfo: {
				phase: 'general',
				suggestion: false,
				sld: 'shakibisawesome',
				tld: 'site',
				availability: true,
				premium: false,
				registry_premium: false,
				aftermarket: false,
				tmch: false,
				domain: 'shakibisawesome.site',
				domain_partner: 'rodas',
			},
			propertyID: '47',
			name: '.site',
			action: 'add',
			currency: 'USD',
			type: 'domains',
			level: 'site',
			category: 'domains',
			privacyAvailable: true,
			terms: [
				{
					price: '4.99',
					basePrice: '4.99',
					promos: 'site_register_499_1o',
					offerId: 174625,
					term: 12,
					masters: '1854',
				},
				{
					price: '16.98',
					basePrice: '16.98',
					promos: 'site_register_1698_2o',
					offerId: 174628,
					term: 24,
					masters: '1854',
				},
				{
					price: '28.97',
					basePrice: '28.97',
					promos: 'site_register_2897_3o',
					offerId: 174631,
					term: 36,
					masters: '1854',
				},
				{
					price: '40.96',
					basePrice: '40.96',
					promos: 'site_register_4096_4o',
					offerId: 174634,
					term: 48,
					masters: '1854',
				},
				{
					price: '52.95',
					basePrice: '52.95',
					promos: 'site_register_5295_5o',
					offerId: 174637,
					term: 60,
					masters: '1854',
				},
			],
		},
		{
			domainInfo: {
				phase: 'general',
				suggestion: false,
				sld: 'shakibisawesome',
				tld: 'website',
				availability: true,
				premium: false,
				registry_premium: false,
				aftermarket: false,
				tmch: false,
				domain: 'shakibisawesome.website',
				domain_partner: 'rodas',
			},
			propertyID: '47',
			name: '.website',
			action: 'add',
			currency: 'USD',
			type: 'domains',
			level: 'website',
			category: 'domains',
			privacyAvailable: true,
			terms: [
				{
					price: '3.99',
					basePrice: '3.99',
					promos: 'website_register_399_1o',
					offerId: 174670,
					term: 12,
					masters: '1689',
				},
				{
					price: '14.98',
					basePrice: '14.98',
					promos: 'website_register_1498_2o',
					offerId: 174673,
					term: 24,
					masters: '1689',
				},
				{
					price: '25.97',
					basePrice: '25.97',
					promos: 'website_register_2597_3o',
					offerId: 174676,
					term: 36,
					masters: '1689',
				},
				{
					price: '36.96',
					basePrice: '36.96',
					promos: 'website_register_3696_4o',
					offerId: 174679,
					term: 48,
					masters: '1689',
				},
				{
					price: '47.95',
					basePrice: '47.95',
					promos: 'website_register_4795_5o',
					offerId: 174682,
					term: 60,
					masters: '1689',
				},
			],
		},
		{
			domainInfo: {
				phase: 'general',
				suggestion: false,
				sld: 'shakibisawesome',
				tld: 'blog',
				availability: true,
				premium: false,
				registry_premium: false,
				aftermarket: false,
				tmch: false,
				domain: 'shakibisawesome.blog',
				domain_partner: 'rodas',
			},
			propertyID: '47',
			name: '.blog',
			action: 'add',
			currency: 'USD',
			type: 'domains',
			level: 'blog',
			category: 'domains',
			privacyAvailable: true,
			terms: [
				{
					price: '6.99',
					basePrice: '6.99',
					promos: 'blog_register_699_1o',
					offerId: 392822,
					term: 12,
					masters: '2009',
				},
				{
					price: '33.98',
					basePrice: '33.98',
					promos: 'blog_register_3398_2o',
					offerId: 392825,
					term: 24,
					masters: '2009',
				},
				{
					price: '60.97',
					basePrice: '60.97',
					promos: 'blog_register_6097_3o',
					offerId: 392828,
					term: 36,
					masters: '2009',
				},
				{
					price: '87.96',
					basePrice: '87.96',
					promos: 'blog_register_8796_4o',
					offerId: 392831,
					term: 48,
					masters: '2009',
				},
				{
					price: '114.95',
					basePrice: '114.95',
					promos: 'blog_register_11495_5o',
					offerId: 392834,
					term: 60,
					masters: '2009',
				},
			],
		},
		{
			domainInfo: {
				phase: 'general',
				suggestion: false,
				sld: 'shakibisawesome',
				tld: 'co',
				availability: true,
				premium: false,
				registry_premium: false,
				aftermarket: false,
				tmch: false,
				domain: 'shakibisawesome.co',
				domain_partner: 'rodas',
			},
			propertyID: '47',
			name: '.co',
			action: 'add',
			currency: 'USD',
			type: 'domains',
			level: 'co',
			category: 'domains',
			privacyAvailable: true,
			terms: [
				{
					price: '27.99',
					basePrice: '27.99',
					promos: 'co_register_2799_1o',
					offerId: 505976,
					term: 12,
					masters: '957',
				},
				{
					price: '55.98',
					basePrice: '55.98',
					promos: 'co_register_5598_2o',
					offerId: 505981,
					term: 24,
					masters: '957',
				},
				{
					price: '83.97',
					basePrice: '83.97',
					promos: 'co_register_8397_3o',
					offerId: 505986,
					term: 36,
					masters: '957',
				},
				{
					price: '111.96',
					basePrice: '111.96',
					promos: 'co_register_11196_4o',
					offerId: 505991,
					term: 48,
					masters: '957',
				},
				{
					price: '139.95',
					basePrice: '139.95',
					promos: 'co_register_13995_5o',
					offerId: 505996,
					term: 60,
					masters: '957',
				},
			],
		},
		{
			domainInfo: {
				phase: 'general',
				suggestion: false,
				sld: 'shakibisawesome',
				tld: 'me',
				availability: true,
				premium: false,
				registry_premium: false,
				aftermarket: false,
				tmch: false,
				domain: 'shakibisawesome.me',
				domain_partner: 'rodas',
			},
			propertyID: '47',
			name: '.me',
			action: 'add',
			currency: 'USD',
			type: 'domains',
			level: 'me',
			category: 'domains',
			privacyAvailable: true,
			terms: [
				{
					price: '3.99',
					basePrice: '3.99',
					promos: 'me_register_399_1o',
					offerId: 152865,
					term: 12,
					masters: '950',
				},
				{
					price: '21.98',
					basePrice: '21.98',
					promos: 'me_register_2198_2o',
					offerId: 524126,
					term: 24,
					masters: '950',
				},
				{
					price: '39.97',
					basePrice: '39.97',
					promos: 'me_register_3997_3o',
					offerId: 524131,
					term: 36,
					masters: '950',
				},
				{
					price: '57.96',
					basePrice: '57.96',
					promos: 'me_register_5796_4o',
					offerId: 524136,
					term: 48,
					masters: '950',
				},
				{
					price: '75.95',
					basePrice: '75.95',
					promos: 'me_register_7595_5o',
					offerId: 524141,
					term: 60,
					masters: '950',
				},
			],
		},
		{
			domainInfo: {
				phase: 'general',
				suggestion: false,
				sld: 'shakibisawesome',
				tld: 'live',
				availability: true,
				premium: false,
				registry_premium: false,
				aftermarket: false,
				tmch: false,
				domain: 'shakibisawesome.live',
				domain_partner: 'rodas',
			},
			propertyID: '47',
			name: '.live',
			action: 'add',
			currency: 'USD',
			type: 'domains',
			level: 'live',
			category: 'domains',
			privacyAvailable: true,
			terms: [
				{
					price: '2.99',
					basePrice: '2.99',
					promos: 'live_register_299_1o',
					offerId: 444659,
					term: 12,
					masters: '1939',
				},
				{
					price: '30.98',
					basePrice: '30.98',
					promos: 'live_register_3098_2o',
					offerId: 444662,
					term: 24,
					masters: '1939',
				},
				{
					price: '58.97',
					basePrice: '58.97',
					promos: 'live_register_5897_3o',
					offerId: 444665,
					term: 36,
					masters: '1939',
				},
				{
					price: '86.96',
					basePrice: '86.96',
					promos: 'live_register_8696_4o',
					offerId: 444668,
					term: 48,
					masters: '1939',
				},
				{
					price: '114.95',
					basePrice: '114.95',
					promos: 'live_register_11495_5o',
					offerId: 444671,
					term: 60,
					masters: '1939',
				},
			],
		},
		{
			domainInfo: {
				phase: 'general',
				suggestion: false,
				sld: 'shakibisawesome',
				tld: 'us',
				availability: true,
				premium: false,
				registry_premium: false,
				aftermarket: false,
				tmch: false,
				domain: 'shakibisawesome.us',
				domain_partner: 'rodas',
			},
			propertyID: '47',
			name: '.us',
			action: 'add',
			currency: 'USD',
			type: 'domains',
			level: 'us',
			category: 'domains',
			privacyAvailable: false,
			terms: [
				{
					price: '8.99',
					basePrice: '8.99',
					promos: 'us_register_899_1o',
					offerId: 76505,
					term: 12,
					masters: '946',
				},
				{
					price: '17.98',
					basePrice: '17.98',
					promos: 'us_register_1798_2o',
					offerId: 160300,
					term: 24,
					masters: '946',
				},
				{
					price: '26.97',
					basePrice: '26.97',
					promos: 'us_register_2697_3o',
					offerId: 160301,
					term: 36,
					masters: '946',
				},
				{
					price: '35.96',
					basePrice: '35.96',
					promos: 'us_register_3596_4o',
					offerId: 160302,
					term: 48,
					masters: '946',
				},
				{
					price: '44.95',
					basePrice: '44.95',
					promos: 'us_register_4495_5o',
					offerId: 160303,
					term: 60,
					masters: '946',
				},
			],
		},
		{
			domainInfo: {
				phase: 'general',
				suggestion: false,
				sld: 'shakibisawesome',
				tld: 'design',
				availability: true,
				premium: false,
				registry_premium: false,
				aftermarket: false,
				tmch: false,
				domain: 'shakibisawesome.design',
				domain_partner: 'rodas',
			},
			propertyID: '47',
			name: '.design',
			action: 'add',
			currency: 'USD',
			type: 'domains',
			level: 'design',
			category: 'domains',
			privacyAvailable: true,
			terms: [
				{
					price: '13.99',
					basePrice: '13.99',
					promos: 'design_register_1399_1o',
					offerId: 462846,
					term: 12,
					masters: '1832',
				},
				{
					price: '53.98',
					basePrice: '53.98',
					promos: 'design_register_5398_2o',
					offerId: 462851,
					term: 24,
					masters: '1832',
				},
				{
					price: '93.97',
					basePrice: '93.97',
					promos: 'design_register_9397_3o',
					offerId: 462856,
					term: 36,
					masters: '1832',
				},
				{
					price: '133.96',
					basePrice: '133.96',
					promos: 'design_register_13396_4o',
					offerId: 462861,
					term: 48,
					masters: '1832',
				},
				{
					price: '173.95',
					basePrice: '173.95',
					promos: 'design_register_17395_5o',
					offerId: 462866,
					term: 60,
					masters: '1832',
				},
			],
		},
		{
			domainInfo: {
				phase: 'general',
				suggestion: false,
				sld: 'shakibisawesome',
				tld: 'ca',
				availability: true,
				premium: false,
				registry_premium: false,
				aftermarket: false,
				tmch: false,
				domain: 'shakibisawesome.ca',
				domain_partner: 'enom',
				eap: false,
			},
			propertyID: '47',
			name: '.ca',
			action: 'add',
			currency: 'USD',
			type: 'domains',
			level: 'ca',
			category: 'domains',
			privacyAvailable: false,
			terms: [
				{
					price: '12.99',
					basePrice: '12.99',
					promos: 'ca_register_1299_1o',
					offerId: 74357,
					term: 12,
					masters: '952',
				},
				{
					price: '25.98',
					basePrice: '25.98',
					promos: 'ca_register_2598_2o',
					offerId: 74358,
					term: 24,
					masters: '952',
				},
				{
					price: '38.97',
					basePrice: '38.97',
					promos: 'ca_register_3897_3o',
					offerId: 74359,
					term: 36,
					masters: '952',
				},
				{
					price: '51.96',
					basePrice: '51.96',
					promos: 'ca_register_5196_4o',
					offerId: 74360,
					term: 48,
					masters: '952',
				},
				{
					price: '64.95',
					basePrice: '64.95',
					promos: 'ca_register_6495_5o',
					offerId: 74361,
					term: 60,
					masters: '952',
				},
			],
		},
		{
			domainInfo: {
				phase: 'general',
				suggestion: false,
				sld: 'shakibisawesome',
				tld: 'biz',
				availability: true,
				premium: false,
				registry_premium: false,
				aftermarket: false,
				tmch: false,
				domain: 'shakibisawesome.biz',
				domain_partner: 'rodas',
			},
			propertyID: '47',
			name: '.biz',
			action: 'add',
			currency: 'USD',
			type: 'domains',
			level: 'biz',
			category: 'domains',
			privacyAvailable: true,
			terms: [
				{
					price: '16.99',
					basePrice: '16.99',
					promos: 'biz_register_1699_1o',
					offerId: 74297,
					term: 12,
					masters: '940',
				},
				{
					price: '33.98',
					basePrice: '33.98',
					promos: 'biz_register_3398_2o',
					offerId: 74298,
					term: 24,
					masters: '940',
				},
				{
					price: '50.97',
					basePrice: '50.97',
					promos: 'biz_register_5097_3o',
					offerId: 74299,
					term: 36,
					masters: '940',
				},
				{
					price: '67.96',
					basePrice: '67.96',
					promos: 'biz_register_6796_4o',
					offerId: 74300,
					term: 48,
					masters: '940',
				},
				{
					price: '84.95',
					basePrice: '84.95',
					promos: 'biz_register_8495_5o',
					offerId: 152348,
					term: 60,
					masters: '940',
				},
			],
		},
		{
			domainInfo: {
				phase: 'general',
				suggestion: false,
				sld: 'shakibisawesome',
				tld: 'host',
				availability: true,
				premium: false,
				registry_premium: false,
				aftermarket: false,
				tmch: false,
				domain: 'shakibisawesome.host',
				domain_partner: 'rodas',
			},
			propertyID: '47',
			name: '.host',
			action: 'add',
			currency: 'USD',
			type: 'domains',
			level: 'host',
			category: 'domains',
			privacyAvailable: true,
			terms: [
				{
					price: '19.99',
					basePrice: '19.99',
					promos: 'host_register_1999_1o',
					offerId: 166757,
					term: 12,
					masters: '1707',
				},
				{
					price: '49.98',
					basePrice: '49.98',
					promos: 'host_register_4998_2o',
					offerId: 174799,
					term: 24,
					masters: '1707',
				},
				{
					price: '79.97',
					basePrice: '79.97',
					promos: 'host_register_7997_3o',
					offerId: 174802,
					term: 36,
					masters: '1707',
				},
				{
					price: '109.96',
					basePrice: '109.96',
					promos: 'host_register_10996_4o',
					offerId: 174805,
					term: 48,
					masters: '1707',
				},
				{
					price: '139.95',
					basePrice: '139.95',
					promos: 'host_register_13995_5o',
					offerId: 174808,
					term: 60,
					masters: '1707',
				},
			],
		},
		{
			domainInfo: {
				phase: 'general',
				suggestion: false,
				sld: 'shakibisawesome',
				tld: 'press',
				availability: true,
				premium: false,
				registry_premium: false,
				aftermarket: false,
				tmch: false,
				domain: 'shakibisawesome.press',
				domain_partner: 'rodas',
			},
			propertyID: '47',
			name: '.press',
			action: 'add',
			currency: 'USD',
			type: 'domains',
			level: 'press',
			category: 'domains',
			privacyAvailable: true,
			terms: [
				{
					price: '19.99',
					basePrice: '19.99',
					promos: 'press_register_1999_1o',
					offerId: 166772,
					term: 12,
					masters: '1688',
				},
				{
					price: '49.98',
					basePrice: '49.98',
					promos: 'press_register_4998_2o',
					offerId: 174841,
					term: 24,
					masters: '1688',
				},
				{
					price: '79.97',
					basePrice: '79.97',
					promos: 'press_register_7997_3o',
					offerId: 174844,
					term: 36,
					masters: '1688',
				},
				{
					price: '109.96',
					basePrice: '109.96',
					promos: 'press_register_10996_4o',
					offerId: 174847,
					term: 48,
					masters: '1688',
				},
				{
					price: '139.95',
					basePrice: '139.95',
					promos: 'press_register_13995_5o',
					offerId: 174850,
					term: 60,
					masters: '1688',
				},
			],
		},
		{
			domainInfo: {
				phase: 'general',
				suggestion: false,
				sld: 'shakibisawesome',
				tld: 'io',
				availability: true,
				premium: false,
				registry_premium: false,
				aftermarket: false,
				tmch: false,
				domain: 'shakibisawesome.io',
				domain_partner: 'enom',
				eap: false,
			},
			propertyID: '47',
			name: '.io',
			action: 'add',
			currency: 'USD',
			type: 'domains',
			level: 'io',
			category: 'domains',
			privacyAvailable: false,
			terms: [
				{
					price: '47.99',
					basePrice: '47.99',
					promos: 'io_register_4799_1o',
					offerId: 460235,
					term: 12,
					masters: '1908',
				},
				{
					price: '95.98',
					basePrice: '95.98',
					promos: 'io_register_9598_2o',
					offerId: 460238,
					term: 24,
					masters: '1908',
				},
				{
					price: '143.97',
					basePrice: '143.97',
					promos: 'io_register_14397_3o',
					offerId: 460241,
					term: 36,
					masters: '1908',
				},
				{
					price: '191.96',
					basePrice: '191.96',
					promos: 'io_register_19196_4o',
					offerId: 460244,
					term: 48,
					masters: '1908',
				},
				{
					price: '239.95',
					basePrice: '239.95',
					promos: 'io_register_23995_5o',
					offerId: 460247,
					term: 60,
					masters: '1908',
				},
			],
		},
		{
			domainInfo: {
				phase: 'general',
				suggestion: false,
				sld: 'shakibisawesome',
				tld: 'club',
				availability: true,
				premium: false,
				registry_premium: false,
				aftermarket: false,
				tmch: false,
				domain: 'shakibisawesome.club',
				domain_partner: 'rodas',
			},
			propertyID: '47',
			name: '.club',
			action: 'add',
			currency: 'USD',
			type: 'domains',
			level: 'club',
			category: 'domains',
			privacyAvailable: true,
			terms: [
				{
					price: '14.99',
					basePrice: '14.99',
					promos: 'club_register_1499_1o',
					offerId: 461210,
					term: 12,
					masters: '1563',
				},
				{
					price: '29.98',
					basePrice: '29.98',
					promos: 'club_register_2998_2o',
					offerId: 461213,
					term: 24,
					masters: '1563',
				},
				{
					price: '44.97',
					basePrice: '44.97',
					promos: 'club_register_4497_3o',
					offerId: 461216,
					term: 36,
					masters: '1563',
				},
				{
					price: '59.96',
					basePrice: '59.96',
					promos: 'club_register_5996_4o',
					offerId: 461219,
					term: 48,
					masters: '1563',
				},
				{
					price: '74.95',
					basePrice: '74.95',
					promos: 'club_register_7495_5o',
					offerId: 461222,
					term: 60,
					masters: '1563',
				},
			],
		},
		{
			domainInfo: {
				phase: 'general',
				suggestion: false,
				sld: 'shakibisawesome',
				tld: 'info',
				availability: true,
				premium: false,
				registry_premium: false,
				aftermarket: false,
				tmch: false,
				domain: 'shakibisawesome.info',
				domain_partner: 'rodas',
			},
			propertyID: '47',
			name: '.info',
			action: 'add',
			currency: 'USD',
			type: 'domains',
			level: 'info',
			category: 'domains',
			privacyAvailable: true,
			terms: [
				{
					price: '3.99',
					basePrice: '3.99',
					promos: 'info_register_399_1o',
					offerId: 455441,
					term: 12,
					masters: '942',
				},
				{
					price: '23.98',
					basePrice: '23.98',
					promos: 'info_register_2398_2o',
					offerId: 75217,
					term: 24,
					masters: '942',
				},
				{
					price: '43.97',
					basePrice: '43.97',
					promos: 'info_register_4397_3o',
					offerId: 523416,
					term: 36,
					masters: '942',
				},
				{
					price: '63.96',
					basePrice: '63.96',
					promos: 'info_register_6396_4o',
					offerId: 77515,
					term: 48,
					masters: '942',
				},
				{
					price: '83.95',
					basePrice: '83.95',
					promos: 'info_register_8395_5o',
					offerId: 523421,
					term: 60,
					masters: '942',
				},
			],
		},
	],
	fakePrivacy: {
		type: '2092',
		category: 'domains',
		currency: 'USD',
		privacyAvailable: false,
		terms: [
			{
				price: '8.99',
				basePrice: '8.99',
				promos: 'dir_base01_a',
				offerId: 404645,
				regularRate: 0.75,
				monthlyPrice: 0.75,
				discount: '0%',
				term: 12,
				masters: '2092',
			},
			{
				price: '17.98',
				basePrice: '17.98',
				promos: 'dir_base01_24',
				offerId: 443933,
				regularRate: 0.75,
				monthlyPrice: 0.75,
				discount: '0%',
				term: 24,
				masters: '2092',
			},
			{
				price: '26.97',
				basePrice: '26.97',
				promos: 'dir_base01_36',
				offerId: 443936,
				regularRate: 0.75,
				monthlyPrice: 0.75,
				discount: '0%',
				term: 36,
				masters: '2092',
			},
			{
				price: '35.96',
				basePrice: '35.96',
				promos: 'dir_base01_48',
				offerId: 449651,
				regularRate: 0.75,
				monthlyPrice: 0.75,
				discount: '0%',
				term: 48,
				masters: '2092',
			},
			{
				price: '44.95',
				basePrice: '44.95',
				promos: 'dir_base01_60',
				offerId: 443939,
				regularRate: 0.75,
				monthlyPrice: 0.75,
				discount: '0%',
				term: 60,
				masters: '2092',
			},
		],
		level: 'dir_base01_',
		action: 'add',
		propertyID: '47',
		isInternalUser: false,
		name: 'Domain Privacy + Protection',
	},
	fakeAddon: {
		type: '980',
		level: 'reg_disc01_',
		action: 'add',
		propertyID: '47',
		currency: 'USD',
		isInternalUser: false,
		name: 'Basic Hosting Plan',
		category: 'hosting',
		privacyAvailable: false,
		terms: [
			{
				price: '23.88',
				basePrice: '23.88',
				promos: 'reg_disc01_a',
				offerId: 80204,
				regularRate: 4.99,
				monthlyPrice: 1.99,
				discount: '60%',
				term: 12,
				masters: '980',
			},
			{
				price: '68.88',
				basePrice: '68.88',
				promos: 'reg_disc01_24',
				offerId: 425456,
				regularRate: 4.99,
				monthlyPrice: 2.87,
				discount: '42%',
				term: 24,
				masters: '980',
			},
			{
				price: '113.88',
				basePrice: '113.88',
				promos: 'reg_disc01_36',
				offerId: 425459,
				regularRate: 4.99,
				monthlyPrice: 3.16,
				discount: '37%',
				term: 36,
				masters: '980',
			},
		],
	},
};

const fakeFetchDomains = (formattedDomain) =>
	new Promise((resolve) => {
		const { sld, tld } = extractDomain(formattedDomain);
		const firstDomain = {
			...FAKE.fakeDomains[0],
			domainInfo: {
				...FAKE.fakeDomains[0].domainInfo,
				sld,
				tld,
				availability: true,
				domain: formattedDomain,
			},
		};
		setTimeout(() => resolve([firstDomain, ...FAKE.fakeDomains]), 1000);
	});

const fakeFetchPrivacy = () =>
	new Promise((resolve) => {
		setTimeout(() => resolve(FAKE.fakePrivacy), 1000);
	});

const fakeFetchAddon = () =>
	new Promise((resolve) => {
		setTimeout(() => resolve(FAKE.fakePrivacy), 1000);
	});

export { fakeFetchDomains, fakeFetchPrivacy, fakeFetchAddon };
